# Generated by Django 5.2.8 on 2025-11-21 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('copyright', 'Infracción de derechos de autor'), ('offensive', 'Contenido ofensivo'), ('spam', 'Spam / contenido engañoso'), ('other', 'Otro')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('review', 'En revisión'), ('resolved', 'Resuelto'), ('rejected', 'Rechazado')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reporter_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_reports', to='artists.artist')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='songs.song')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='abuse_songr_status_310671_idx'), models.Index(fields=['reason'], name='abuse_songr_reason_b0a381_idx')],
            },
        ),
    ]
